#!/usr/bin/python
print " Compliment Machine!"
print " Compliments every 5 minutes"
print " Made by @Realgagenichols"
print " Keep window open ;)"
#made by Gage Nichols 
#follow @Realgagenichols
import easygui
import time
import sys
import os
easygui.msgbox ("You're the best!", title="Reminder")
time.sleep (300)
easygui.msgbox ("You're doing great!", title="Reminder")
time.sleep (300)
easygui.msgbox ("Have an amazing day!", title="Reminder")
time.sleep (300)
easygui.msgbox ("You deserve the best!", title="Reminder")
time.sleep (300)
easygui.msgbox ("You look great today!", title="Reminder")
time.sleep (300)
easygui.msgbox ("You're really smart!", title="Reminder")
time.sleep (300)
easygui.msgbox ("You're perfect!", title="Reminder")
time.sleep (300)
easygui.msgbox ("You light up the room!", title="Reminder")
time.sleep (300)
easygui.msgbox ("You're strong!", title="Reminder")
time.sleep (300)
easygui.msgbox ("You're an awesome friend!", title="Reminder")
time.sleep (300)
easygui.msgbox ("You have a great sense of humor!", title="Reminder")
time.sleep (300)
easygui.msgbox ("On a scale of 1 to 10 you're an 11!", title="Reminder")
time.sleep (300)
easygui.msgbox ("You're beautiful!", title="Reminder")
time.sleep (300)
easygui.msgbox ("You bring out the best in people!", title="Reminder")
time.sleep (300)
easygui.msgbox ("You're a great listener!", title="Reminder")
time.sleep (300)
easygui.msgbox ("Being around you makes everything better!", title="Reminder")
time.sleep (300)
easygui.msgbox ("You're wonderful!", title="Reminder")
time.sleep (300)
easygui.msgbox ("You're one of a kind", title="Reminder")
time.sleep (300)
easygui.msgbox ("You're inspiring!", title="Reminder")
time.sleep (300)
easygui.msgbox ("You make everything better!", title="Reminder")
time.sleep (300)
easygui.msgbox ("You have the best ideas!", title="Reminder")
time.sleep (300)
easygui.msgbox ("You're a great example to others!", title="Reminder")
time.sleep (300)
easygui.msgbox ("You always know just what to say!", title="Reminder")
time.sleep (300)
easygui.msgbox ("You're more fun than bubble wrap!", title="Reminder")
time.sleep (300)
easygui.msgbox ("You're Magnificent!", title="Reminder")
time.sleep (300)
easygui.msgbox ("People are lucky to have you!", title="Reminder")
time.sleep (300)
easygui.msgbox ("You're like a breath of fresh air!", title="Reminder")
time.sleep (300)
easygui.msgbox ("You're so thoughtful!", title="Reminder")
time.sleep (300)
easygui.msgbox ("Your creative potential is limitless!", title="Reminder")
time.sleep (300)
easygui.msgbox ("You're irresistible!", title="Reminder")
time.sleep (300)
easygui.msgbox ("Any team would be lucky to have you!", title="Reminder")
time.sleep (300)
easygui.msgbox ("You're extraordinary!", title="Reminder")
time.sleep (300)
easygui.msgbox ("You're someone's reason to smile!", title="Reminder")
time.sleep (300)
easygui.msgbox ("You're really special!", title="Reminder")
time.sleep (300)
easygui.msgbox ("I like your style!", title="Reminder")
time.sleep (300)
easygui.msgbox ("You're tremendous!", title="Reminder")
time.sleep (300)
easygui.msgbox ("Your ideas are briliant!", title="Reminder")
time.sleep (300)
easygui.msgbox ("You're so impressive!", title="Reminder")
time.sleep (300)
easygui.msgbox ("You're so loved!", title="Reminder")
time.sleep (300)
easygui.msgbox ("You always look amazing!", title="Reminder")
time.sleep (300)
easygui.msgbox ("You're so smart!", title="Reminder")
time.sleep (300)
easygui.msgbox ("You're really cool!", title="Reminder")
time.sleep (300)
easygui.msgbox ("You're #1!", title="Reminder")
time.sleep (300)
easygui.msgbox ("You're a star!", title="Reminder")
time.sleep (300)
easygui.msgbox ("You're the bees knees!", title="Reminder")
time.sleep (300)
easygui.msgbox ("You have good taste!", title="Reminder")
time.sleep (300)
easygui.msgbox ("You're infatuating!", title="Reminder")
time.sleep (300)
easygui.msgbox ("You're absoloutley astounding!", title="Reminder")
time.sleep (300)
easygui.msgbox ("Be happy you deserve the best!", title="Reminder")
time.sleep (300)
easygui.msgbox ("<3", title="Reminder")
time.sleep (300)
def restart_program():
	"""restarts program"""
	python = sys.executable
	os.execl(python, python, * sys.argv)
#made by Gage Nichols 
#follow @Realgagenichols
